import "reflect-metadata";
import express from "express";
import swaggerUi from "swagger-ui-express";
import { error_middleware } from "./middleware/error_middleware.js";
import { config } from "./lib/config.js";
import { logger } from "./lib/logger.js";

/**
 * Express app entry point for the Auth Service.
 * tsoa-generated routes and OpenAPI spec are registered here.
 * Repositories are instantiated here and injected into Services via DI.
 */
const app = express();

app.use(express.json());

// OpenAPI docs — auto-generated by tsoa from controller decorators
// app.use("/docs", swaggerUi.serve, swaggerUi.setup(openapi_spec));

// tsoa-generated routes will be registered here after running `bun run generate`
// import { RegisterRoutes } from "./routes/routes.js";
// RegisterRoutes(app);

app.use(error_middleware);

app.listen(config.PORT, () => {
  logger.info(`Auth Service running on port ${config.PORT}`);
});

export default app;
