"""
Repository layer for AI tables.

Each repository class encapsulates all SQLAlchemy ORM queries for its
corresponding table.  Business logic lives in services; repositories only
read/write the database and return domain models.

Rule: never import DTOs or HTTP-related types here.
Rule: return SQLAlchemy model instances or Python primitives only.
"""

import uuid
from collections.abc import Sequence

from sqlalchemy import func, select, update
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.ai import (
    AiConversation,
    AiMessage,
    AiMessageRole,
    AiSuggestion,
    AiSuggestionStatus,
)


# ---------------------------------------------------------------------------
# AiConversationRepository
# ---------------------------------------------------------------------------


class AiConversationRepository:
    """
    Data-access layer for the ai_conversations table.

    All methods accept a SQLAlchemy AsyncSession so the caller can
    control transaction boundaries (auto-committed by the FastAPI
    dependency via get_db_session).
    """

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def create(
        self,
        document_id: uuid.UUID,
        user_id: uuid.UUID,
        title: str | None = None,
    ) -> AiConversation:
        """
        Insert a new conversation row and return it with all defaults populated.

        Args:
            document_id: The document this conversation is attached to.
            user_id: The authenticated user who owns this conversation.
            title: Optional display title (auto-generated by the caller if None).

        Returns:
            The persisted AiConversation instance.
        """
        conversation = AiConversation(
            document_id=document_id,
            user_id=user_id,
            title=title,
        )
        self._session.add(conversation)
        await self._session.flush()  # populate server-default fields (id, created_at)
        await self._session.refresh(conversation)
        return conversation

    async def get_by_id(self, conversation_id: uuid.UUID) -> AiConversation | None:
        """
        Fetch a single conversation by its primary key.

        Returns None if not found.
        """
        result = await self._session.execute(
            select(AiConversation).where(AiConversation.id == conversation_id)
        )
        return result.scalar_one_or_none()

    async def list_for_document(
        self,
        document_id: uuid.UUID,
        user_id: uuid.UUID,
        limit: int = 50,
        offset: int = 0,
    ) -> tuple[Sequence[AiConversation], int]:
        """
        List conversations for a specific document and user, newest first.

        Args:
            document_id: Scope to this document.
            user_id: Scope to this user.
            limit: Maximum rows to return.
            offset: Number of rows to skip for pagination.

        Returns:
            A (rows, total_count) tuple.
        """
        base_where = (
            (AiConversation.document_id == document_id)
            & (AiConversation.user_id == user_id)
        )

        count_result = await self._session.execute(
            select(func.count()).select_from(AiConversation).where(base_where)
        )
        total: int = count_result.scalar_one()

        rows_result = await self._session.execute(
            select(AiConversation)
            .where(base_where)
            .order_by(AiConversation.updated_at.desc())
            .limit(limit)
            .offset(offset)
        )
        rows = rows_result.scalars().all()

        return rows, total

    async def delete(self, conversation_id: uuid.UUID) -> bool:
        """
        Hard-delete a conversation (cascades to messages and suggestions).

        Returns True if a row was deleted, False if not found.
        """
        conversation = await self.get_by_id(conversation_id)
        if conversation is None:
            return False
        await self._session.delete(conversation)
        return True


# ---------------------------------------------------------------------------
# AiMessageRepository
# ---------------------------------------------------------------------------


class AiMessageRepository:
    """Data-access layer for the ai_messages table."""

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def create(
        self,
        conversation_id: uuid.UUID,
        role: AiMessageRole,
        content: str,
        token_count: int | None = None,
    ) -> AiMessage:
        """
        Insert a new message row.

        Args:
            conversation_id: Parent conversation UUID.
            role: Message role (user/assistant/system/tool).
            content: Raw text content of the message.
            token_count: Optional LLM token usage for this message.

        Returns:
            The persisted AiMessage instance.
        """
        message = AiMessage(
            conversation_id=conversation_id,
            role=role,
            content=content,
            token_count=token_count,
        )
        self._session.add(message)
        await self._session.flush()
        await self._session.refresh(message)
        return message

    async def list_for_conversation(
        self,
        conversation_id: uuid.UUID,
    ) -> Sequence[AiMessage]:
        """
        Return all messages in a conversation ordered by creation time (ascending).

        Args:
            conversation_id: The target conversation UUID.

        Returns:
            Ordered list of AiMessage instances.
        """
        result = await self._session.execute(
            select(AiMessage)
            .where(AiMessage.conversation_id == conversation_id)
            .order_by(AiMessage.created_at.asc())
        )
        return result.scalars().all()

    async def update_token_count(
        self,
        message_id: uuid.UUID,
        token_count: int,
    ) -> None:
        """
        Patch the token_count field of an existing message after the LLM finishes.

        Args:
            message_id: Target message UUID.
            token_count: Final token count from the LLM response.
        """
        await self._session.execute(
            update(AiMessage)
            .where(AiMessage.id == message_id)
            .values(token_count=token_count)
        )


# ---------------------------------------------------------------------------
# AiSuggestionRepository
# ---------------------------------------------------------------------------


class AiSuggestionRepository:
    """Data-access layer for the ai_suggestions table."""

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def create(
        self,
        conversation_id: uuid.UUID,
        document_id: uuid.UUID,
        suggested_text: str,
        message_id: uuid.UUID | None = None,
        original_text: str | None = None,
        position_start: int | None = None,
        position_end: int | None = None,
    ) -> AiSuggestion:
        """
        Insert a new suggestion in 'proposed' state.

        Args:
            conversation_id: Parent conversation UUID.
            document_id: Target document UUID.
            suggested_text: The AI-generated text proposal.
            message_id: Optional assistant message that produced this suggestion.
            original_text: The text that would be replaced (nullable).
            position_start: Character offset start in the document (nullable).
            position_end: Character offset end in the document (nullable).

        Returns:
            The persisted AiSuggestion instance.
        """
        suggestion = AiSuggestion(
            conversation_id=conversation_id,
            document_id=document_id,
            suggested_text=suggested_text,
            message_id=message_id,
            original_text=original_text,
            position_start=position_start,
            position_end=position_end,
            status=AiSuggestionStatus.proposed,
        )
        self._session.add(suggestion)
        await self._session.flush()
        await self._session.refresh(suggestion)
        return suggestion

    async def get_by_id(self, suggestion_id: uuid.UUID) -> AiSuggestion | None:
        """Fetch a suggestion by primary key. Returns None if not found."""
        result = await self._session.execute(
            select(AiSuggestion).where(AiSuggestion.id == suggestion_id)
        )
        return result.scalar_one_or_none()

    async def update_status(
        self,
        suggestion_id: uuid.UUID,
        status: AiSuggestionStatus,
    ) -> AiSuggestion | None:
        """
        Transition a suggestion to a new lifecycle status.

        Args:
            suggestion_id: Target suggestion UUID.
            status: New status (applied/dismissed/superseded).

        Returns:
            The updated AiSuggestion, or None if not found.
        """
        await self._session.execute(
            update(AiSuggestion)
            .where(AiSuggestion.id == suggestion_id)
            .values(status=status)
        )
        return await self.get_by_id(suggestion_id)

    async def list_for_conversation(
        self,
        conversation_id: uuid.UUID,
        status: AiSuggestionStatus | None = None,
    ) -> Sequence[AiSuggestion]:
        """
        List suggestions for a conversation, optionally filtered by status.

        Args:
            conversation_id: Target conversation UUID.
            status: If provided, filter to this status only.

        Returns:
            List of AiSuggestion instances ordered by creation time.
        """
        stmt = (
            select(AiSuggestion)
            .where(AiSuggestion.conversation_id == conversation_id)
            .order_by(AiSuggestion.created_at.asc())
        )
        if status is not None:
            stmt = stmt.where(AiSuggestion.status == status)

        result = await self._session.execute(stmt)
        return result.scalars().all()
