"""
Repository layer for AI tables.

Each repository class encapsulates all SQLAlchemy ORM queries for its
corresponding table.  Business logic lives in services; repositories only
read/write the database and return domain models.

Rule: never import DTOs or HTTP-related types here.
Rule: return SQLAlchemy model instances or Python primitives only.
"""

import uuid
from collections.abc import Sequence
from typing import TypedDict

from sqlalchemy import Column, MetaData, Table, Text, cast, func, literal, select, update
from sqlalchemy import Enum as SAEnum
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.types import TIMESTAMP

from models.ai import (
    AiConversation,
    AiMessage,
    AiMessageRole,
    AiSuggestion,
    AiSuggestionStatus,
    DocumentEmbedding,
)
from schemas.ai import ToolCallTrace


class DocumentMetadata(TypedDict):
    """Server-resolved metadata for a document owned by another service."""

    document_id: uuid.UUID
    workspace_id: uuid.UUID
    document_title: str | None


class DocumentAccessResult(TypedDict):
    """Document metadata plus explicit access flags for one user."""

    document_id: uuid.UUID
    workspace_id: uuid.UUID
    document_title: str | None
    visibility: str
    workspace_role: str | None
    has_access: bool


class WorkspaceSearchHit(TypedDict):
    """Primitive search row returned from workspace-scoped retrieval."""

    document_id: uuid.UUID
    workspace_id: uuid.UUID
    chunk_index: int
    chunk_text: str
    document_title: str | None
    is_current_document: bool
    distance: float


document_visibility_enum = SAEnum(
    "private",
    "workspace",
    "link",
    "public",
    name="document_visibility",
)
documents_table = Table(
    "documents",
    MetaData(),
    Column("id", PGUUID(as_uuid=True)),
    Column("workspace_id", PGUUID(as_uuid=True)),
    Column("title", Text),
    Column("visibility", document_visibility_enum),
    Column("deleted_at", TIMESTAMP(timezone=True)),
    schema="public",
)
workspaces_table = Table(
    "workspaces",
    MetaData(),
    Column("id", PGUUID(as_uuid=True)),
    Column("deleted_at", TIMESTAMP(timezone=True)),
    schema="public",
)
workspace_members_table = Table(
    "workspace_members",
    MetaData(),
    Column("workspace_id", PGUUID(as_uuid=True)),
    Column("user_id", PGUUID(as_uuid=True)),
    Column(
        "role",
        SAEnum("owner", "admin", "member", name="workspace_member_role"),
    ),
    Column("revoked_at", TIMESTAMP(timezone=True)),
    schema="public",
)
document_members_table = Table(
    "document_members",
    MetaData(),
    Column("document_id", PGUUID(as_uuid=True)),
    Column("user_id", PGUUID(as_uuid=True)),
    schema="public",
)

# ---------------------------------------------------------------------------
# AiConversationRepository
# ---------------------------------------------------------------------------


class AiConversationRepository:
    """
    Data-access layer for the ai_conversations table.

    All methods accept a SQLAlchemy AsyncSession so the caller can
    control transaction boundaries (auto-committed by the FastAPI
    dependency via get_db_session).
    """

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def create(
        self,
        document_id: uuid.UUID,
        user_id: uuid.UUID,
        title: str | None = None,
    ) -> AiConversation:
        """
        Insert a new conversation row and return it with all defaults populated.

        Args:
            document_id: The document this conversation is attached to.
            user_id: The authenticated user who owns this conversation.
            title: Optional display title (auto-generated by the caller if None).

        Returns:
            The persisted AiConversation instance.
        """
        conversation = AiConversation(
            document_id=document_id,
            user_id=user_id,
            title=title,
        )
        self._session.add(conversation)
        await self._session.flush()  # populate server-default fields (id, created_at)
        await self._session.refresh(conversation)
        return conversation

    async def get_by_id(self, conversation_id: uuid.UUID) -> AiConversation | None:
        """
        Fetch a single conversation by its primary key.

        Returns None if not found.
        """
        result = await self._session.execute(
            select(AiConversation).where(AiConversation.id == conversation_id)
        )
        return result.scalar_one_or_none()

    async def get_by_id_for_user(
        self,
        conversation_id: uuid.UUID,
        user_id: uuid.UUID,
    ) -> AiConversation | None:
        """
        Fetch a single conversation by id, scoped to an owner user.

        Args:
            conversation_id: Conversation UUID.
            user_id: Owner user UUID.

        Returns:
            AiConversation when found and owned by the user, otherwise None.
        """
        result = await self._session.execute(
            select(AiConversation).where(
                (AiConversation.id == conversation_id) & (AiConversation.user_id == user_id)
            )
        )
        return result.scalar_one_or_none()

    async def list_for_document(
        self,
        document_id: uuid.UUID,
        user_id: uuid.UUID,
        limit: int = 50,
        offset: int = 0,
    ) -> tuple[Sequence[AiConversation], int]:
        """
        List conversations for a specific document and user, newest first.

        Args:
            document_id: Scope to this document.
            user_id: Scope to this user.
            limit: Maximum rows to return.
            offset: Number of rows to skip for pagination.

        Returns:
            A (rows, total_count) tuple.
        """
        base_where = (AiConversation.document_id == document_id) & (
            AiConversation.user_id == user_id
        )

        count_result = await self._session.execute(
            select(func.count()).select_from(AiConversation).where(base_where)
        )
        total: int = count_result.scalar_one()

        rows_result = await self._session.execute(
            select(AiConversation)
            .where(base_where)
            .order_by(AiConversation.updated_at.desc())
            .limit(limit)
            .offset(offset)
        )
        rows = rows_result.scalars().all()

        return rows, total

    async def delete(self, conversation_id: uuid.UUID) -> bool:
        """
        Hard-delete a conversation (cascades to messages and suggestions).

        Returns True if a row was deleted, False if not found.
        """
        conversation = await self.get_by_id(conversation_id)
        if conversation is None:
            return False
        await self._session.delete(conversation)
        return True

    async def touch_updated_at(self, conversation_id: uuid.UUID) -> None:
        """
        Update the conversation updated_at timestamp to now().

        Called whenever a new message is appended so ordering by recency works.
        """
        await self._session.execute(
            update(AiConversation)
            .where(AiConversation.id == conversation_id)
            .values(updated_at=func.now())
        )

    async def set_title(self, conversation_id: uuid.UUID, title: str) -> None:
        """
        Persist a generated title only when the conversation is still untitled.

        This avoids overwriting a title that may have been set concurrently.
        """
        await self._session.execute(
            update(AiConversation)
            .where((AiConversation.id == conversation_id) & (AiConversation.title.is_(None)))
            .values(title=title)
        )


# ---------------------------------------------------------------------------
# AiMessageRepository
# ---------------------------------------------------------------------------


class AiMessageRepository:
    """Data-access layer for the ai_messages table."""

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def create(
        self,
        conversation_id: uuid.UUID,
        role: AiMessageRole,
        content: str,
        token_count: int | None = None,
        tool_calls: list[ToolCallTrace | dict[str, object] | str] | None = None,
    ) -> AiMessage:
        """
        Insert a new message row.

        Args:
            conversation_id: Parent conversation UUID.
            role: Message role (user/assistant/system/tool).
            content: Raw text content of the message.
            token_count: Optional LLM token usage for this message.
            tool_calls: Ordered structured tool traces used to produce the message.

        Returns:
            The persisted AiMessage instance.
        """
        message = AiMessage(
            conversation_id=conversation_id,
            role=role,
            content=content,
            token_count=token_count,
            tool_calls=[
                item.model_dump(mode="json") if isinstance(item, ToolCallTrace) else item
                for item in list(tool_calls or [])
            ],
        )
        self._session.add(message)
        await self._session.flush()
        await self._session.refresh(message)
        return message

    async def list_for_conversation(
        self,
        conversation_id: uuid.UUID,
    ) -> Sequence[AiMessage]:
        """
        Return all messages in a conversation ordered by creation time (ascending).

        Args:
            conversation_id: The target conversation UUID.

        Returns:
            Ordered list of AiMessage instances.
        """
        result = await self._session.execute(
            select(AiMessage)
            .where(AiMessage.conversation_id == conversation_id)
            .order_by(AiMessage.created_at.asc())
        )
        return result.scalars().all()

    async def update_token_count(
        self,
        message_id: uuid.UUID,
        token_count: int,
    ) -> None:
        """
        Patch the token_count field of an existing message after the LLM finishes.

        Args:
            message_id: Target message UUID.
            token_count: Final token count from the LLM response.
        """
        await self._session.execute(
            update(AiMessage).where(AiMessage.id == message_id).values(token_count=token_count)
        )


# ---------------------------------------------------------------------------
# AiSuggestionRepository
# ---------------------------------------------------------------------------


class AiSuggestionRepository:
    """Data-access layer for the ai_suggestions table."""

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def create(
        self,
        conversation_id: uuid.UUID,
        document_id: uuid.UUID,
        suggested_text: str,
        message_id: uuid.UUID | None = None,
        original_text: str | None = None,
        position_start: int | None = None,
        position_end: int | None = None,
    ) -> AiSuggestion:
        """
        Insert a new suggestion in 'proposed' state.

        Args:
            conversation_id: Parent conversation UUID.
            document_id: Target document UUID.
            suggested_text: The AI-generated text proposal.
            message_id: Optional assistant message that produced this suggestion.
            original_text: The text that would be replaced (nullable).
            position_start: Character offset start in the document (nullable).
            position_end: Character offset end in the document (nullable).

        Returns:
            The persisted AiSuggestion instance.
        """
        suggestion = AiSuggestion(
            conversation_id=conversation_id,
            document_id=document_id,
            suggested_text=suggested_text,
            message_id=message_id,
            original_text=original_text,
            position_start=position_start,
            position_end=position_end,
            status=AiSuggestionStatus.proposed,
        )
        self._session.add(suggestion)
        await self._session.flush()
        await self._session.refresh(suggestion)
        return suggestion

    async def get_by_id(self, suggestion_id: uuid.UUID) -> AiSuggestion | None:
        """Fetch a suggestion by primary key. Returns None if not found."""
        result = await self._session.execute(
            select(AiSuggestion).where(AiSuggestion.id == suggestion_id)
        )
        return result.scalar_one_or_none()

    async def update_status(
        self,
        suggestion_id: uuid.UUID,
        status: AiSuggestionStatus,
    ) -> AiSuggestion | None:
        """
        Transition a suggestion to a new lifecycle status.

        Args:
            suggestion_id: Target suggestion UUID.
            status: New status (applied/dismissed/superseded).

        Returns:
            The updated AiSuggestion, or None if not found.
        """
        await self._session.execute(
            update(AiSuggestion).where(AiSuggestion.id == suggestion_id).values(status=status)
        )
        return await self.get_by_id(suggestion_id)

    async def list_for_conversation(
        self,
        conversation_id: uuid.UUID,
        status: AiSuggestionStatus | None = None,
    ) -> Sequence[AiSuggestion]:
        """
        List suggestions for a conversation, optionally filtered by status.

        Args:
            conversation_id: Target conversation UUID.
            status: If provided, filter to this status only.

        Returns:
            List of AiSuggestion instances ordered by creation time.
        """
        stmt = (
            select(AiSuggestion)
            .where(AiSuggestion.conversation_id == conversation_id)
            .order_by(AiSuggestion.created_at.asc())
        )
        if status is not None:
            stmt = stmt.where(AiSuggestion.status == status)

        result = await self._session.execute(stmt)
        return result.scalars().all()


# ---------------------------------------------------------------------------
# DocumentEmbeddingRepository
# ---------------------------------------------------------------------------


class DocumentEmbeddingRepository:
    """
    Data-access layer for the document_embeddings table.

    Provides chunk upsert, bulk insert, cosine-similarity vector search,
    and document-level delete operations.
    """

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def bulk_insert(
        self,
        document_id: uuid.UUID,
        workspace_id: uuid.UUID,
        chunks: list[tuple[int, str, list[float]]],
    ) -> int:
        """
        Insert multiple embedding chunks for a document in one operation.

        Existing embeddings for the document are deleted first so re-indexing
        is idempotent (delete-then-insert pattern).

        Args:
            document_id: Target document UUID.
            chunks: List of (chunk_index, chunk_text, embedding_vector) tuples.

        Returns:
            Number of chunks inserted.
        """
        await self.delete_for_document(document_id)

        rows = [
            DocumentEmbedding(
                document_id=document_id,
                workspace_id=workspace_id,
                chunk_index=index,
                chunk_text=text,
                embedding=vector,
            )
            for index, text, vector in chunks
        ]
        self._session.add_all(rows)
        await self._session.flush()
        return len(rows)

    async def get_document_metadata(self, document_id: uuid.UUID) -> DocumentMetadata | None:
        """Return workspace-scoped metadata for a document from public.documents."""

        result = await self._session.execute(
            select(
                documents_table.c.id,
                documents_table.c.workspace_id,
                documents_table.c.title,
            ).where(
                (documents_table.c.id == document_id) & (documents_table.c.deleted_at.is_(None))
            )
        )
        row = result.one_or_none()
        if row is None:
            return None
        return {
            "document_id": row.id,
            "workspace_id": row.workspace_id,
            "document_title": row.title,
        }

    async def search_workspace(
        self,
        query_embedding: list[float],
        document_id: uuid.UUID,
        user_id: uuid.UUID,
        top_k: int = 5,
        exclude_current_document: bool = False,
    ) -> list[WorkspaceSearchHit]:
        """
        Find the top-k most similar chunks within the current document's workspace.

        Args:
            query_embedding: The embedded query vector (1536 dims).
            document_id: Current document used to resolve the workspace scope.
            user_id: Authenticated user used to filter source-document visibility.
            top_k: Maximum number of results to return.
            exclude_current_document: When true, omit chunks from the current document.

        Returns:
            List of primitive search-hit dictionaries, closest first.
        """
        from pgvector.sqlalchemy import Vector

        private_visibility = literal("private", type_=document_visibility_enum)
        distance_col = DocumentEmbedding.embedding.cosine_distance(
            cast(query_embedding, Vector(1536))
        )
        current_document = documents_table.alias("current_document")
        source_document = documents_table.alias("source_document")
        source_workspace_member = workspace_members_table.alias("source_workspace_member")
        source_document_member = document_members_table.alias("source_document_member")

        stmt = (
            select(
                DocumentEmbedding.document_id.label("document_id"),
                source_document.c.workspace_id.label("resolved_workspace_id"),
                DocumentEmbedding.chunk_index.label("chunk_index"),
                DocumentEmbedding.chunk_text.label("chunk_text"),
                source_document.c.title.label("document_title"),
                (DocumentEmbedding.document_id == document_id).label("is_current_document"),
                distance_col.label("distance"),
            )
            .join(source_document, DocumentEmbedding.document_id == source_document.c.id)
            .join(current_document, current_document.c.id == document_id)
            .outerjoin(
                source_workspace_member,
                (source_workspace_member.c.workspace_id == source_document.c.workspace_id)
                & (source_workspace_member.c.user_id == user_id)
                & (source_workspace_member.c.revoked_at.is_(None)),
            )
            .outerjoin(
                source_document_member,
                (source_document_member.c.document_id == source_document.c.id)
                & (source_document_member.c.user_id == user_id),
            )
            .where(
                (source_document.c.workspace_id == current_document.c.workspace_id)
                & (source_document.c.deleted_at.is_(None))
                & (current_document.c.deleted_at.is_(None))
                & (
                    (
                        (source_document.c.visibility != private_visibility)
                        & (source_workspace_member.c.user_id.is_not(None))
                    )
                    | (
                        (source_document.c.visibility == private_visibility)
                        & (
                            source_document_member.c.user_id.is_not(None)
                            | source_workspace_member.c.role.in_(["owner", "admin"])
                        )
                    )
                )
            )
            .order_by(distance_col)
            .limit(top_k)
        )
        if exclude_current_document:
            stmt = stmt.where(DocumentEmbedding.document_id != document_id)

        result = await self._session.execute(stmt)
        hits: list[WorkspaceSearchHit] = []
        for row in result.all():
            hits.append(
                {
                    "document_id": row.document_id,
                    "workspace_id": row.resolved_workspace_id,
                    "chunk_index": row.chunk_index,
                    "chunk_text": row.chunk_text,
                    "document_title": row.document_title,
                    "is_current_document": row.is_current_document,
                    "distance": row.distance,
                }
            )
        return hits

    async def delete_for_document(self, document_id: uuid.UUID) -> int:
        """
        Delete all embedding chunks for a document.

        Args:
            document_id: Target document UUID.

        Returns:
            Number of rows deleted.
        """
        from sqlalchemy import delete as sql_delete

        result = await self._session.execute(
            sql_delete(DocumentEmbedding).where(DocumentEmbedding.document_id == document_id)
        )
        rowcount = getattr(result, "rowcount", 0)
        return int(rowcount or 0)


class DocumentAccessRepository:
    """Shared-data authorization helper for document-scoped AI routes."""

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def get_document_access(
        self,
        document_id: uuid.UUID,
        user_id: uuid.UUID,
    ) -> DocumentAccessResult | None:
        """Return active document metadata and whether the user may access it."""

        workspace = workspaces_table.alias("workspace")
        workspace_member = workspace_members_table.alias("workspace_member")
        document_member = document_members_table.alias("document_member")

        result = await self._session.execute(
            select(
                documents_table.c.id,
                documents_table.c.workspace_id,
                documents_table.c.title,
                documents_table.c.visibility,
                workspace_member.c.role.label("workspace_member_role"),
                workspace_member.c.user_id.label("workspace_member_user_id"),
                document_member.c.user_id.label("document_member_user_id"),
            )
            .select_from(documents_table)
            .outerjoin(
                workspace,
                (workspace.c.id == documents_table.c.workspace_id)
                & (workspace.c.deleted_at.is_(None)),
            )
            .outerjoin(
                workspace_member,
                (workspace_member.c.workspace_id == documents_table.c.workspace_id)
                & (workspace_member.c.user_id == user_id)
                & (workspace_member.c.revoked_at.is_(None))
                & (workspace.c.id.is_not(None)),
            )
            .outerjoin(
                document_member,
                (document_member.c.document_id == documents_table.c.id)
                & (document_member.c.user_id == user_id),
            )
            .where((documents_table.c.id == document_id) & (documents_table.c.deleted_at.is_(None)))
            .limit(1)
        )
        row = result.one_or_none()
        if row is None:
            return None
        has_workspace_member = row.workspace_member_user_id is not None
        has_document_member = row.document_member_user_id is not None
        is_workspace_admin = row.workspace_member_role in {"owner", "admin"}
        has_access = False
        if row.visibility == "private":
            has_access = has_document_member or is_workspace_admin
        else:
            has_access = has_workspace_member
        return {
            "document_id": row.id,
            "workspace_id": row.workspace_id,
            "document_title": row.title,
            "visibility": row.visibility,
            "workspace_role": row.workspace_member_role,
            "has_access": has_access,
        }
